### ISSUE TITLE
v3.901.Preview - Interpolation Issues

### ISSUE THREAD

**Issue by kenmcd** [playbeing/dinish#11]
v3.901.(2024-08-24).Preview-Interpolation-Issues
File: DINishPreview-Variable-VF.ttf

figure 8 - element order
/eight/eight.osf/eight.tlf/eight.tosf/eight.dnom/eight.numr/eightsuperior
![2024-08-27_17-05-16](https://github.com/user-attachments/assets/283ccce1-61e2-40f1-a6d3-3a423c5edddd)

punctuation - element order
/colon/semicolon/quotedblbase/ellipsis
![2024-08-27_17-08-07](https://github.com/user-attachments/assets/34c9fdd5-3eca-422c-8d0d-517306637115)

hungarian umlaut - element order issues
/Ohungarumlaut/ohungarumlaut/Uhungarumlaut/uhungarumlaut/hungarumlaut/hungarumlautcmb
![2024-08-27_17-10-31](https://github.com/user-attachments/assets/afc669a9-47f6-46a0-85d2-1b281b9124c1)

caron alt - height and position issues
/Lcaron/lcaron/caroncmb.alt/tcaron
![2024-08-27_17-15-43](https://github.com/user-attachments/assets/a56259c7-0200-4623-80c6-b9b6528331c0)

/B/Vecyr - element order
![2024-08-27_17-21-05](https://github.com/user-attachments/assets/a810be08-452e-4201-b99f-41b1b32d2d10)

/copyright/section - different start points
![2024-08-27_17-25-28](https://github.com/user-attachments/assets/0c18085c-8780-4254-b29f-0cc96a373cf9)

/divisionslash - side bearing issues
![2024-08-27_17-29-15](https://github.com/user-attachments/assets/e33eb596-3dc9-4d3e-8064-b0f037a3c79e)

/Ocenteredtilde - side bearings
![2024-08-27_17-35-36](https://github.com/user-attachments/assets/7a6870c1-b911-4bfe-bc85-410164e0b269)

More later...

**Comment by kenmcd** [comment]
CHECKS - v3.904.(2024-08-28)

/quotedblbase/ellipsis
still some element order issues
![2024-08-29_11-57-33](https://github.com/user-attachments/assets/f32e8599-0bc1-4a26-97cf-d51a1865f0a7)

/Lcaron/lcaron/caroncmb.alt/tcaron
still tight at Weight 800 and Width 100
![2024-08-29_12-06-13](https://github.com/user-attachments/assets/400f80bb-85b0-4710-9575-95e3aebc9781)

**Comment by driehuis** [comment]
I think I tackled all of these.

Way back when, I had a tool that could spit out a PDF (or a bunch of png's, I don't remember), that showed the same glyph from different fonts superimposed in different colors. That would make this job so much easier... Of course, the tool predated variable fonts, so it probably requires an update if not a rewrite to be able to handle interpolations from the same font, but I don't fancy rewriting it from scratch. Even though it's probably not rocket surgery...

**Comment by driehuis** [comment]
It's late, I missed your last update.... I'll revisit the borkjed glyphs. Thanks for bearing with me.

**Comment by driehuis** [comment]
It helps if one actually saves all changes... Also found the cause of the misplaced components in quotedblbase and ellipsis (my script does not actually handle ordering components properly, and I forgot to check). Anyway, saved the complete set of Slovak caron fixes this time, and adjusted the side bearings of lcaron to introduce a smidgeon of air in the bold only. This is how it was intended in the first place. Your test cases now look good in the vartype.com animator. I will upload 3.905 soonish.

**Comment by driehuis** [comment]
DINish v4.002 is out with fixes for the issues you raised. @kenmcd , thanks again for your work and words of encouragement!
