### ISSUE TITLE
Accessing OpenType features in CSS

### ISSUE THREAD

**Issue by Crissov** [playbeing/dinish#13]
The documentation readme suggests to use `font-feature-settings` to access OTF features in CSS. This low-level approach does not cascade well and should only be chosen if there is no higher-level feature available. For alternative digit glyphs, there is [`font-variant-numeric`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric), for instance.

**Comment by driehuis** [comment]
Thanks for the feedback, I guess it shows that I haven't tracked CSS development for a while... I'll update the documentation when DINish 4.0 drops (any day now...)

**Comment by driehuis** [comment]
Updated the recommendation on the front page. Updating the other pages, as well as the website itself, is on the todo list.
