### ISSUE TITLE
bold italic

### ISSUE THREAD

**Issue by arjpar** [playbeing/dinish#6]
Hi!
Would it be possible to add bold italics to this font?

**Comment by driehuis** [comment]
Yes, this should be possible. I'll put it on the todo list. Just out of curiosity, are you aware that there is really not a lot of difference between the Italic variants of Dinish, and letting your word processor or browser apply a 12° faux Italic? There is a handful of glyphs in Italic that are not slanted as per typographical convention, that's really the biggest difference.

**Comment by arjpar** [comment]
> are you aware that there is really not a lot of difference between the Italic variants of Dinish, and letting your word processor or browser apply a 12° faux Italic?

I am aware. I would like to respectfully & kindly suggest that fonts are expected to come with at least 4 variants: Bold, Bold Italic, Italic, Regular. This is because most word processors and text formatting use one of those 4 styles.

**Comment by driehuis** [comment]
For the record: if you think AI has a bad reputation of hallucinating about things that just aren't known, you haven't seen word processors handle missing fonts and filling in the blanks. Often with surprisingly good results. With most glyphs in DINish Italic just being slanted Regular glyphs, I sincerely doubt many people will see the difference between DINish v3.007 and DINish v3.008 BoldItalic in their word processor, regardless if they're using MS Office or LibreOffice. I even doubt if InDesign or Scribus users would notice...

That said, your request presented me with the opportunity to tackle an inconsistency in DINish that has irked me from day one, and in the process clean up the build process and even stumble upon a missing glyph in Mongolian!

DINish now comes in an orthoganal set, and is one step closer to a variable font. Thanks for your insistance!

**Comment by driehuis** [comment]
Closing #6
