### ISSUE TITLE
Cyrillic

### ISSUE THREAD

**Issue by alabotski** [playbeing/dinish#7]
Beautiful font, but unfortunately there is no support for Cyrillic... Can you add it?

**Comment by driehuis** [comment]
Cyrillic glyphs are available in an experimental version of DINish created by StefanPeev. You can find it at https://github.com/StefanPeev/dinish/tree/cyrillic/fonts. Please note that this version has not received the same level of quality control as the published version of DINish.

Cyrillic will be included in a future version of DINish, but I cannot promise a timeline.

**Comment by driehuis** [comment]
Version v3.006 was just released, with Stefan's gorgeous Cyrillic glyphs. Please give it a spin and let us know how it works out for you!

**Comment by alabotski** [comment]
Cool thank you

Michael Crichton
[Airframe_](https://en.wikipedia.org/wiki/Airframe_(novel))

Dinish
[Screenshot_20240610-080107](https://github.com/playbeing/dinish/assets/439337/359dd871-bcc9-45e4-8a2e-9478b22f15d5)
DinishCondensed
[Screenshot_20240610-080116](https://github.com/playbeing/dinish/assets/439337/22d78ef1-434e-46c9-b8e7-6ea85f999593)
DinishExpanded
[Screenshot_20240610-080123](https://github.com/playbeing/dinish/assets/439337/eab1dca0-706b-435a-b812-530436f3353c)

**Comment by driehuis** [comment]
Thanks for your feedback!
